"""add login & base tables

Revision ID: 2406857f4c34
Revises: 8e95e77a5eeb
Create Date: 2025-12-10 19:02:35.722938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2406857f4c34'
down_revision: Union[str, Sequence[str], None] = '8e95e77a5eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_ip_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_cidrs', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('for_admin_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_login_ip_policies_id'), 'login_ip_policies', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_site_code'), 'sites', ['site_code'], unique=True)
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_id'), 'offices', ['id'], unique=False)
    op.create_index(op.f('ix_offices_office_code'), 'offices', ['office_code'], unique=True)
    op.create_table('admin_password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_employee_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('admin_comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_password_reset_requests_id'), 'admin_password_reset_requests', ['id'], unique=False)
    op.create_index(op.f('ix_admin_password_reset_requests_target_employee_id'), 'admin_password_reset_requests', ['target_employee_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('requested_ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_employee_id'), 'password_reset_tokens', ['employee_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('user_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_user_mfa_id'), 'user_mfa', ['id'], unique=False)
    op.add_column('employees', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('employees', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('employees', sa.Column('office_id', sa.Integer(), nullable=False))
    op.add_column('employees', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('employees', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('login_ip_policy_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('employees', 'employee_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'employees', 'offices', ['office_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'login_ip_policies', ['login_ip_policy_id'], ['id'])
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.alter_column('employees', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'employee_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'last_login_at')
    op.drop_column('employees', 'login_ip_policy_id')
    op.drop_column('employees', 'must_change_password')
    op.drop_column('employees', 'is_active')
    op.drop_column('employees', 'is_admin')
    op.drop_column('employees', 'hashed_password')
    op.drop_column('employees', 'office_id')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_index(op.f('ix_user_mfa_id'), table_name='user_mfa')
    op.drop_table('user_mfa')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_employee_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_admin_password_reset_requests_target_employee_id'), table_name='admin_password_reset_requests')
    op.drop_index(op.f('ix_admin_password_reset_requests_id'), table_name='admin_password_reset_requests')
    op.drop_table('admin_password_reset_requests')
    op.drop_index(op.f('ix_offices_office_code'), table_name='offices')
    op.drop_index(op.f('ix_offices_id'), table_name='offices')
    op.drop_table('offices')
    op.drop_index(op.f('ix_sites_site_code'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_login_ip_policies_id'), table_name='login_ip_policies')
    op.drop_table('login_ip_policies')
    # ### end Alembic commands ###
