"""add user flags

Revision ID: 2a88fe9ef77f
Revises: 2406857f4c34
Create Date: 2025-12-11 15:43:20.272899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a88fe9ef77f'
down_revision: Union[str, Sequence[str], None] = '2406857f4c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_password_reset_requests', sa.Column('target_user_id', sa.Integer(), nullable=False))
    op.add_column('admin_password_reset_requests', sa.Column('requested_by_user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_admin_password_reset_requests_target_employee_id'), table_name='admin_password_reset_requests')
    op.create_index(op.f('ix_admin_password_reset_requests_target_user_id'), 'admin_password_reset_requests', ['target_user_id'], unique=False)
    op.drop_constraint(op.f('admin_password_reset_requests_target_employee_id_fkey'), 'admin_password_reset_requests', type_='foreignkey')
    op.drop_constraint(op.f('admin_password_reset_requests_requested_by_employee_id_fkey'), 'admin_password_reset_requests', type_='foreignkey')
    op.create_foreign_key(None, 'admin_password_reset_requests', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'admin_password_reset_requests', 'users', ['target_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('admin_password_reset_requests', 'target_employee_id')
    op.drop_column('admin_password_reset_requests', 'requested_by_employee_id')
    op.add_column('employees', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('employees', sa.Column('hired_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('employees_login_ip_policy_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'last_login_at')
    op.drop_column('employees', 'login_ip_policy_id')
    op.drop_column('employees', 'is_active')
    op.drop_column('employees', 'must_change_password')
    op.drop_column('employees', 'hashed_password')
    op.drop_column('employees', 'is_admin')
    op.add_column('password_reset_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_employee_id'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_constraint(op.f('password_reset_tokens_employee_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('password_reset_tokens', 'employee_id')
    op.add_column('user_mfa', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_mfa_employee_id_key'), 'user_mfa', type_='unique')
    op.create_unique_constraint(None, 'user_mfa', ['user_id'])
    op.drop_constraint(op.f('user_mfa_employee_id_fkey'), 'user_mfa', type_='foreignkey')
    op.create_foreign_key(None, 'user_mfa', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_mfa', 'employee_id')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('login_ip_policy_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using="employee_id::integer",)
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_grade'), table_name='users')
    op.create_foreign_key(None, 'users', 'login_ip_policies', ['login_ip_policy_id'], ['id'])
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'])
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_grade'), 'users', ['grade'], unique=False)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.alter_column('users', 'employee_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'login_ip_policy_id')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'is_active')
    op.add_column('user_mfa', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_mfa', type_='foreignkey')
    op.create_foreign_key(op.f('user_mfa_employee_id_fkey'), 'user_mfa', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_mfa', type_='unique')
    op.create_unique_constraint(op.f('user_mfa_employee_id_key'), 'user_mfa', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_mfa', 'user_id')
    op.add_column('password_reset_tokens', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_employee_id_fkey'), 'password_reset_tokens', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_employee_id'), 'password_reset_tokens', ['employee_id'], unique=False)
    op.drop_column('password_reset_tokens', 'user_id')
    op.add_column('employees', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('login_ip_policy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_login_ip_policy_id_fkey'), 'employees', 'login_ip_policies', ['login_ip_policy_id'], ['id'])
    op.drop_column('employees', 'hired_at')
    op.drop_column('employees', 'status')
    op.add_column('admin_password_reset_requests', sa.Column('requested_by_employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admin_password_reset_requests', sa.Column('target_employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin_password_reset_requests', type_='foreignkey')
    op.drop_constraint(None, 'admin_password_reset_requests', type_='foreignkey')
    op.create_foreign_key(op.f('admin_password_reset_requests_requested_by_employee_id_fkey'), 'admin_password_reset_requests', 'employees', ['requested_by_employee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('admin_password_reset_requests_target_employee_id_fkey'), 'admin_password_reset_requests', 'employees', ['target_employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_admin_password_reset_requests_target_user_id'), table_name='admin_password_reset_requests')
    op.create_index(op.f('ix_admin_password_reset_requests_target_employee_id'), 'admin_password_reset_requests', ['target_employee_id'], unique=False)
    op.drop_column('admin_password_reset_requests', 'requested_by_user_id')
    op.drop_column('admin_password_reset_requests', 'target_user_id')
    # ### end Alembic commands ###
