"""add role fields to grades

Revision ID: 8732ae770aee
Revises: caaaf21bcfff
Create Date: 2025-12-13 16:54:13.676567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8732ae770aee'
down_revision: Union[str, Sequence[str], None] = 'caaaf21bcfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('participates_in_evaluation', sa.Boolean(), nullable=True))
    op.add_column('grades', sa.Column('role_key', sa.String(length=30), nullable=False, server_default='employee'))
    op.add_column('grades', sa.Column('can_evaluate', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('grades', sa.Column('default_participates', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('grades', sa.Column('evaluated_as_grade_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_grades_can_evaluate'), 'grades', ['can_evaluate'], unique=False)
    op.create_index(op.f('ix_grades_default_participates'), 'grades', ['default_participates'], unique=False)
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_role_key'), 'grades', ['role_key'], unique=False)
    op.drop_constraint(op.f('uq_users_employee_id'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_employee_id', 'users', ['employee_id'])
    op.drop_constraint(op.f('users_employee_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_employee_id_fkey'), 'users', 'employees', ['employee_id'], ['id'])
    op.drop_constraint('uq_user_employee_id', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_employee_id'), 'users', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_grades_role_key'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_default_participates'), table_name='grades')
    op.drop_index(op.f('ix_grades_can_evaluate'), table_name='grades')
    op.drop_column('grades', 'evaluated_as_grade_code')
    op.drop_column('grades', 'default_participates')
    op.drop_column('grades', 'can_evaluate')
    op.drop_column('grades', 'role_key')
    op.drop_column('employees', 'participates_in_evaluation')
    # ### end Alembic commands ###
